spring:
  datasource:
    name: sign
    url: jdbc:mysql://localhost:3306/sign?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: daibiao0619*
    type: com.alibaba.druid.pool.DruidDataSource

upload:
  path: /opt/upload